### ISSUE TITLE
Limit seem to be ignored

### ISSUE THREAD

**Issue by jdahlke** [infopark/crm_connector#17]
`Infopark::Crm::Contact.search(:params => { :q => 'a' }, :limit => 5).size` and 
`Infopark::Crm::Contact.search(:params => { :q => 'a', :limit => 5 }).size` return more than 5 contacts.

I don't know which call is the correct one, but both don't work.

**Comment by apepper** [comment]
`Infopark::Crm::Contact.search(:params => { :q => 'a', :limit => 5 }).within_limit` should do the trick. Otherwise the Enumerator requests all items in batches of 5.

**Comment by jdahlke** [comment]
Exactly what I wanted. Thanks!
